### ISSUE TITLE
Milestone 1 Review

### ISSUE THREAD

**Issue by esrduke95** [esrduke95/finterest#24]
- [x]  Pull down code
- [x]  run it locally
- [x]  create bug tickets
- [x]  place bug tickets in the milestone
- [x]  deploy to firebase
